### ISSUE TITLE
Prevent deletion of previous XMLs

### ISSUE THREAD

**Issue by justaj** [allure-framework/allure-cucumber#27]
Hi all.  Is there a way to automatically prevent deletion of the XMLs allure creates?  After every execution they get deleted so when I generate the report it only includes the last run. Thanks

**Comment by smecsia** [comment]
Unfortunately for now this is not possible due to this unconditional directory cleanup [#L12](https://github.com/allure-framework/allure-cucumber/blob/master/lib/allure-cucumber/formatter.rb#L12).
Probably we should create a separate configuration option for this. But at first I should ask: why do you want to include different runs in the report?

**Comment by justaj** [comment]
Thanks for the quick response!  Two reasons.  First I think it would be great to get a historical trend of the runs.  My plan is to run our tests every morning and it would be nice to look at the months' run and see what failed and how often.  Second I always compare the current run of any test to the previous run.  If there are new failures I always check why.

**Comment by smecsia** [comment]
I believe these cases should not be solved using Allure. Allure is a tool to build a report of a single independent run. Historical trends and statistics should be stored in different place (like Tests Management System). We are developing such system in our company and it solves such problems. Btw we're thinking about open sourcing it soon. Stay in touch.
