### ISSUE TITLE
Similar steps stick together in report 

### ISSUE THREAD

**Issue by SButterfly** [allure-framework/allure-cucumber#41]
Hi, I noticed that if I create scenarios like this

```
Feature: Home tests

  Scenario: Wait
    Given I wait 1 second
    Given I wait 1 second
```

then allure generate only one step:

``` xml
<?xml version="1.0"?>
<ns2:test-suite xmlns="" xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1465998807044" stop="1465998816236">
  <name>Home tests</name>
  <title>Home tests</title>
  <test-cases>
    <test-case start="1465998811928" stop="1465998815831" status="passed">
      <name>Wait</name>
      <title>Wait</title>
      <steps>
        <step start="1465998813076" stop="1465998814082" status="passed">
          <name>I wait 1 second</name>
          <title>I wait 1 second</title>
          <attachments/>
        </step>
      </steps>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="70316747776520"/>
        <label name="host" value="some host"/>
        <label name="feature" value="Home tests"/>
        <label name="story" value="Wait"/>
      </labels>
      <parameters/>
    </test-case>
  </test-cases>
  <labels>
    <label name="severity" value="normal"/>
    <label name="thread" value="70316747776520"/>
    <label name="host" value="some host"/>
  </labels>
</ns2:test-suite>
```

I'm using 0.5.1 version, but it still reproduced in 0.5.3

**Comment by tk8817** [comment]
I am so glad someone reported this, I noticed this last week but totally forgot to open a ticket. This is really bad for us because we use 'generic' steps in a lot of cases which differ only by table input / variable input and allure_cucumber does exactly what you said and only generates the one step. 

@9ikhan this is a pretty serious bug in the grand scheme of things.

**Comment by KorranForce** [comment]
This issue is related to the fact that [allure-ruby-adaptor-api](https://github.com/allure-framework/allure-ruby-adaptor-api) is storing steps of the scenario as hashes with step names as keys. Because of it duplicated steps in scenario don't have their individual identifiers. And adding ids to steps will require to make changes to api of [allure-ruby-adaptor-api](https://github.com/allure-framework/allure-ruby-adaptor-api) as was said here https://github.com/allure-framework/allure-ruby-adaptor-api/issues/21 and accompanying changes in allure-cucumber formatter.

I made variation of this change in my forks of both repos, but they are only for my special case (not using outline, background steps and on old versions of repos). And I did not take care of backward compatibility there but it may be possible (need to think about it - not sure right now).

**Comment by mikesalvia** [comment]
@KorranForce This may be fixed in https://github.com/allure-framework/allure-cucumber/pull/65

**Comment by mikesalvia** [comment]
@9ikhan and @tk8817 Please let me know if it fixes things for you. I can provide monkey patches if needed to test locally till this is merged in.

**Comment by mikesalvia** [comment]
@baev this can be closed.
