### ISSUE TITLE
Any plans to update this?

### ISSUE THREAD

**Issue by symonk** [allure-framework/allure-cucumber#60]
Moving over to ruby from java I would really like to use my favorite reporting, however it doesn't seem to function whatsoever, cucumber being on version ~3.1 and I think this supports maybe 2.0.0? even when using 2.0.0 it is far from ideal especially when using the parallel_tests gem for execution.

I am happy to contribute on this, just wondering if anyone is working on it already etc?

**Comment by tk8817** [comment]
Hey @symonk. As a maintainer, I share your sentiments.

We could likely get this upgraded to support all the features of Cucumber 3 without much hassle. However, the real issue is that the ruby ecosystem is still on Allure 1.0. 

The Yandex folks have not had time to update the allure ruby API bindings which back both the cucumber and rspec adapters.

To answer your query, I do not believe there is active ruby development in any of the 3 repos at this time.

**Comment by baev** [comment]
> The Yandex folks

We are not Yandex folks anymore. 

> just wondering if anyone is working on it already etc?

The problem is that our team has no ruby dev at the moment. Any help are appreciated. Feel free to ask me any questions

**Comment by symonk** [comment]
ok cool, i will start looking into it when I get some time, could be a while tho :( I think the competition to this is really lackluster and would be great to update everything to support modern ruby successfully
